export const Comments = [
  {
    id: 1,
    userName: "احمد",
    text: "شكرًا لاستخدام خدمتنا!",
    likeCount: 7,
    dislikeCount: 3,
    publicationDate: "2023-12-04",
  },
  {
    id: 2,
    userName: "ابو ريم",
    text: "نحن نقدر تقديرك لخدمتنا!",
    likeCount: 2,
    dislikeCount: 1,
    publicationDate: "2023-12-04",
  },
  {
    id: 3,
    userName: "ابو احمد",
    text: "نشكرك على اختيارك لخدمتنا!",
    likeCount: 5,
    dislikeCount: 0,
    publicationDate: "2023-12-04",
  },
  {
    id: 4,
    userName: "سعيد",
    text: "نأمل أن تكون راضيًا عن خدمتنا!",
    likeCount: 1,
    dislikeCount: 4,
    publicationDate: "2023-12-04",
  },
  {
    id: 5,
    userName: "صالح",
    text: "شكرًا جزيلاً على استخدام خدمتنا!",
    likeCount: 8,
    dislikeCount: 2,
    publicationDate: "2023-12-04",
  },
  {
    id: 6,
    userName: "امين",
    text: "نحن نهتم برأيك في خدمتنا!",
    likeCount: 3,
    dislikeCount: 0,
    publicationDate: "2023-12-04",
  },
  {
    id: 7,
    userName: "فهد",
    text: "شكرًا لدعمك لخدمتنا!",
    likeCount: 6,
    dislikeCount: 1,
    publicationDate: "2023-12-04",
  },
  {
    id: 8,
    userName: "سالم",
    text: "نحن نعتز بثقتك في خدمتنا!",
    likeCount: 4,
    dislikeCount: 0,
    publicationDate: "2023-12-04",
  },
];
